-- migration_exam_mappings.sql
-- Tabela para centralizar o mapeamento de nomes de exames entre sistemas (SIMUS -> COMPULAB)

-- Extensao para UUID (se necessario)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS public.exam_mappings (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at timestamptz DEFAULT now(),
    original_name text NOT NULL, -- Nome como aparece no SIMUS ou outros sistemas
    canonical_name text NOT NULL, -- Nome oficial no COMPULAB (ou padrão do lab)
    category text DEFAULT 'exame', -- Para extensões futuras
    CONSTRAINT unique_original_name UNIQUE(original_name)
);

-- Habilitar RLS
ALTER TABLE public.exam_mappings ENABLE ROW LEVEL SECURITY;

-- Política de acesso público (ajuste conforme necessidade de segurança)
DROP POLICY IF EXISTS "Permitir leitura pública exam_mappings" ON public.exam_mappings;
CREATE POLICY "Permitir leitura pública exam_mappings" ON public.exam_mappings FOR SELECT USING (true);

-- Políticas para escrita (necessárias para o Link de Exames)
DROP POLICY IF EXISTS "Permitir escrita exam_mappings" ON public.exam_mappings;
CREATE POLICY "Permitir escrita exam_mappings" ON public.exam_mappings FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir update exam_mappings" ON public.exam_mappings;
CREATE POLICY "Permitir update exam_mappings" ON public.exam_mappings FOR UPDATE USING (true) WITH CHECK (true);

-- Popular com mapeamentos iniciais (extraídos do código legado)
INSERT INTO public.exam_mappings (original_name, canonical_name) VALUES
('ANALISE DE CARACTERES FISICOS, ELEMENTOS E SEDIMENTO DA URINA', 'EXAME QUALITATIVO DE URINA'),
('ANALISE DE CARACTERES FISICOS ELEMENTOS E SEDIMENTO DA URINA', 'EXAME QUALITATIVO DE URINA'),
('ANÁLISE DE CARACTERES FÍSICOS, ELEMENTOS E SEDIMENTO DA URINA', 'EXAME QUALITATIVO DE URINA'),
('HEMOGRAMA COMPLETO', 'HEMOGRAMA'),
('DOSAGEM DE 25 HIDROXIVITAMINA D', 'VITAMINA D25'),
('DOSAGEM DE VITAMINA B12', 'VITAMINA B12'),
('DOSAGEM DE HORMONIO TIREOESTIMULANTE (TSH)', 'TIREOTROFINA (TSH)'),
('DOSAGEM DE HORMONIO TIREOESTIMULANTE TSH', 'TIREOTROFINA (TSH)'),
('DOSAGEM DE TIROXINA LIVRE (T4 LIVRE)', 'TIROXINA LIVRE (T4 LIVRE)'),
('DOSAGEM DE TIROXINA LIVRE T4 LIVRE', 'TIROXINA LIVRE (T4 LIVRE)'),
('DOSAGEM DE TIROXINA LIVRE (T4)', 'TIROXINA LIVRE (T4 LIVRE)'),
('DOSAGEM DE TIROXINA (T4)', 'TIROXINA (T4)'),
('DOSAGEM DE GLICOSE', 'GLICOSE'),
('DOSAGEM DE COLESTEROL TOTAL', 'COLESTEROL TOTAL'),
('DOSAGEM DE COLESTEROL HDL', 'COLESTEROL HDL'),
('DOSAGEM DE COLESTEROL LDL', 'COLESTEROL LDL'),
('DOSAGEM DE TRIGLICERIDEOS', 'TRIGLICERIDEOS'),
('DOSAGEM DE HEMOGLOBINA GLICOSILADA', 'HEMOGLOBINA GLICOSILADA A1C'),
('DOSAGEM DE CREATININA', 'CREATININA'),
('DOSAGEM DE ACIDO URICO', 'ACIDO URICO'),
('DOSAGEM DE UREIA', 'UREIA'),
('DOSAGEM DE MICROALBUMINA NA URINA', 'MICROALBUMINURIA'),
('DOSAGEM DE POTASSIO', 'POTASSIO'),
('DOSAGEM DE SODIO', 'SODIO'),
('DOSAGEM DE CALCIO', 'CALCIO'),
('DOSAGEM DE MAGNESIO', 'MAGNESIO'),
('DOSAGEM DE ANTIGENO PROSTATICO ESPECIFICO (PSA)', 'ANTIGENO PROSTATICO ESPECIFICO'),
('DOSAGEM DE ANTIGENO PROSTATICO ESPECIFICO PSA', 'ANTIGENO PROSTATICO ESPECIFICO'),
('PSA', 'ANTIGENO PROSTATICO ESPECIFICO'),
('DOSAGEM DE FRACAO PROSTATICA DA FOSFATASE ACIDA', 'FOSFATASE ACIDA PROSTATICA'),
('CULTURA DE BACTERIAS P/ IDENTIFICACAO', 'UROCULTURA'),
('CULTURA DE BACTERIAS P IDENTIFICACAO', 'UROCULTURA'),
('DOSAGEM DE TRANSAMINASE GLUTAMICO-OXALACETICA (TGO)', 'GOT'),
('DOSAGEM DE TRANSAMINASE GLUTAMICO-OXALACETICA TGO', 'GOT'),
('DOSAGEM DE TRANSAMINASE GLUTAMICO-PIRUVICA (TGP)', 'GPT'),
('DOSAGEM DE TRANSAMINASE GLUTAMICO-PIRUVICA TGP', 'GPT'),
('DOSAGEM DE GAMA-GLUTAMIL-TRANSFERASE (GAMA GT)', 'GAMA GT'),
('DOSAGEM DE GAMA-GLUTAMIL-TRANSFERASE GAMA GT', 'GAMA GT'),
('DOSAGEM DE FOSFATASE ALCALINA', 'FOSFATASE ALCALINA'),
('DOSAGEM DE BILIRRUBINA TOTAL E FRACOES', 'BILIRRUBINAS'),
('DOSAGEM DE FERRITINA', 'FERRITINA'),
('DOSAGEM DE FERRO SERICO', 'FERRO SERICO'),
('DOSAGEM DE TRANSFERRINA', 'TRANSFERRINA'),
('DOSAGEM DE INSULINA', 'INSULINA'),
('DOSAGEM DE ESTRADIOL', 'ESTRADIOL'),
('DOSAGEM DE CORTISOL', 'CORTISOL'),
('DOSAGEM DE PROLACTINA', 'PROLACTINA'),
('DOSAGEM DE PROGESTERONA', 'PROGESTERONA'),
('DOSAGEM DE TESTOSTERONA LIVRE', 'TESTOSTERONA LIVRE'),
('DOSAGEM DE TESTOSTERONA', 'TESTOSTERONA TOTAL'),
('DOSAGEM DE HORMONIO FOLICULO-ESTIMULANTE (FSH)', 'HORMONIO FOLICULO ESTIMULANTE FSH'),
('DOSAGEM DE HORMONIO FOLICULO-ESTIMULANTE FSH', 'HORMONIO FOLICULO ESTIMULANTE FSH'),
('DOSAGEM DE HORMONIO LUTEINIZANTE (LH)', 'HORMONIO LUTEINIZANTE LH'),
('DOSAGEM DE HORMONIO LUTEINIZANTE LH', 'HORMONIO LUTEINIZANTE LH'),
('DOSAGEM DE GONADOTROFINA CORIONICA HUMANA (HCG, BETA HCG)', 'B-HCG'),
('DOSAGEM DE GONADOTROFINA CORIONICA HUMANA HCG BETA HCG', 'B-HCG'),
('DOSAGEM DE ANDROSTENEDIONA', 'ANDROSTENEDIONA'),
('DOSAGEM DE PROTEINA C REATIVA', 'PROVA DO LATEX A.R.'),
('DOSAGEM DE PROTEINAS TOTAIS E FRACOES', 'PROTEÍNAS TOTAIS E FRAÇÕES'),
('DETERMINAÇÃO DE VELOCIDADE DE HEMOSSEDIMENTAÇÃO (VHS)', 'V S G'),
('DETERMINACAO DE VELOCIDADE DE HEMOSSEDIMENTACAO VHS', 'V S G'),
('DETERMINAÇÃO DE TEMPO E ATIVIDADE DA PROTROMBINA (TAP)', 'TEMPO DE PROTROMBINA'),
('DETERMINACAO DE TEMPO E ATIVIDADE DA PROTROMBINA TAP', 'TEMPO DE PROTROMBINA'),
('DETERMINAÇÃO DE TEMPO DE TROMBOPLASTINA PARCIAL ATIVADA (TTP ATIVADA)', 'TEMPO DE TROMBOPLASTINA ATIVADO (TTPA)'),
('DETERMINACAO DE TEMPO DE TROMBOPLASTINA PARCIAL ATIVADA TTP ATIVADA', 'TEMPO DE TROMBOPLASTINA ATIVADO (TTPA)'),
('PESQUISA DE ANTICORPOS ANTINUCLEO', 'FATOR ANTI NUCLEAR (FAN)'),
('PESQUISA DE ANTICORPOS ANTIMICROSSOMAS', 'ANTI-TIREOPEROXIDASE (ANTI-TPO)'),
('PESQUISA DE ANTICORPOS IGG ANTITOXOPLASMA', 'TOXOPLASMOSE (IFI-IgG)'),
('PESQUISA DE ANTICORPOS IGM ANTITOXOPLASMA', 'TOXOPLASMOSE (IFI-IgM)'),
('PESQUISA DE ANTICORPOS IGG ANTICITOMEGALOVIRUS', 'CITOMEGALOVIRUS IgG'),
('PESQUISA DE ANTICORPOS IGM ANTICITOMEGALOVIRUS', 'CITOMEGALOVIRUS IgM'),
('PESQUISA DE ANTICORPOS IGG CONTRA O VIRUS EPSTEIN-BARR', 'EPSTEIN-BAAR IgG'),
('PESQUISA DE ANTICORPOS IGM CONTRA O VIRUS EPSTEIN-BARR', 'EPSTEIN-BAAR IgM'),
('TESTE NÃO TREPONEMICO P/ DETECÇÃO DE SIFILIS', 'VDRL QUANTITATIVO'),
('TESTE NAO TREPONEMICO P DETECCAO DE SIFILIS', 'VDRL QUANTITATIVO'),
('PESQUISA DE ANTICORPOS CONTRA ANTIGENO DE SUPERFICIE DO VIRUS DA HEPATITE B (ANTI-HBS)', 'ANTI-HBS'),
('PESQUISA DE ANTICORPOS CONTRA ANTIGENO DE SUPERFICIE DO VIRUS DA HEPATITE B ANTI-HBS', 'ANTI-HBS'),
('PESQUISA LABORATORIAL DE ANTIGENO DE SUPERFÍCIE DO VÍRUS DA HEPATITE B (HBSAG)', 'ABsAg (ANTIGENO AUSTRALIA)'),
('PESQUISA LABORATORIAL DE ANTIGENO DE SUPERFICIE DO VIRUS DA HEPATITE B HBSAG', 'ABsAg (ANTIGENO AUSTRALIA)'),
('DETERMINACAO DIRETA E REVERSA DE GRUPO ABO', 'GRUPO SANGUINEO'),
('PESQUISA DE FATOR RH (INCLUI D FRACO)', 'FATOR Rh'),
('TESTE INDIRETO DE ANTIGLOBULINA HUMANA (TIA)', 'COOMBS INDIRETO'),
('DOSAGEM DE CREATINOFOSFOQUINASE (CPK)', 'CREATINOFOSFOQUINASE'),
('DOSAGEM DE CREATINOFOSFOQUINASE CPK', 'CREATINOFOSFOQUINASE'),
('CPK', 'CREATINOFOSFOQUINASE'),
('DOSAGEM DE LIPASE', 'LIPASE'),
('DOSAGEM DE AMILASE', 'AMILASE'),
('PESQUISA LABORATORIAL DE ANTIGENOS DE HIV E/OU ANTICORPOS ANTI-HIV-1 OU ANTI-HIV-2', 'HIV 1/2'),
('PESQUISA LABORATORIAL DE ANTIGENOS DE HIV E OU ANTICORPOS ANTI-HIV-1 OU ANTI-HIV-2', 'HIV 1/2'),
('PESQUISA DE SANGUE OCULTO NAS FEZES', 'SANGUE OCULTO'),
('CLEARANCE DE CREATININA', 'DEPURACAO DA CREATININA ENDOGENA'),
('CONTAGEM DE PLAQUETAS', 'PLAQUETAS'),
('DETERMINACAO DE CAPACIDADE DE FIXACAO DO FERRO', 'CAPACIDADE FERROPEXICA'),
('DETERMINACAO DE CURVA GLICEMICA CLASSICA', 'GLICOSE 1 E 2 HORAS'),
('DOSAGEM DE 17 ALFA HIDROXIPROGESTERONA', '17 HIDROXIPROGESTERONA'),
('DOSAGEM DE ALFA 1 GLICOPROTEINA ACIDA', 'ALFA 1 GLICOPROTEINA ACIDA'),
('DOSAGEM DE FOLATO', 'ACIDO FOLICO'),
('DOSAGEM DE FOSFORO', 'FOSFORO'),
('DOSAGEM DE IMUNOGLOBULINA A', 'IMUNOGLOBULINA A'),
('DOSAGEM DE LITIO', 'LITIO'),
('DOSAGEM DE PARATORMONIO', 'PARATORMONIO'),
('DOSAGEM DE TIREOGLOBULINA', 'TIREOGLOBULINA'),
('DOSAGEM DE TRIIODOTIRONINA', 'TRIIODOTIRONINA T3 RIE'),
('TRIIODOTIRONINA', 'TRIIODOTIRONINA T3 RIE'),
('DOSAGEM DE ZINCO', 'ZINCO'),
('PESQUISA DE ANTICORPOS ANTIESTREPTOLISINA O', 'ANTIESTREPTOLISINA O'),
('PESQUISA DE ANTICORPOS ANTIINSULINA', 'ANTICORPOS ANTI INSULINA'),
('PESQUISA DE ANTIGENO CARCINOEMBRIONARIO', 'ANTIGENO CARCINO EMBRIONICO'),
('PESQUISA DE OVOS E CISTOS DE PARASITAS 1ª AMOSTRA', 'EXAME PARASITOLOGICO DE FEZES 1 O'),
('PESQUISA LABORATORIAL DE ANTICORPOS ANTI HTLV 1 HTLV 2 PARA POPULACAO GERAL', 'HTLV I II'),
('PESQUISA LABORATORIAL DE ANTICORPOS CONTRA O VIRUS DA HEPATITE C (PARA POPULACAO GERAL/EM GESTANTE)', 'ANTI HCV'),
('SANGUE OCULTO', 'PESQUISA DE SANGUE OCULTO FEZES'),
('TIROXINA', 'TIROXINA T4 RIE'),
('PROTEINA C REATIVA', 'PROVA DO LATEX A.R.'),
('G O T', 'GOT'),
('G P T', 'GPT')
ON CONFLICT (original_name) DO UPDATE SET canonical_name = EXCLUDED.canonical_name;
